namespace libciscocdp
{
    using System;

    /// <summary>
    /// A parser exception generated by the CdpParser functions
    /// </summary>
    public class CdpParserException : Exception
    {
        /// <summary>
        /// The buffer upon which the exception occurred
        /// </summary>
        public byte[] Buffer { get; }

        /// <summary>
        /// The position within the parser when the exception occured
        /// </summary>
        public int Index { get; }

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="buffer">The buffer being parsed</param>
        /// <param name="index">The index within the buffer where the exception occurred</param>
        /// <param name="message">The message from the parser</param>
        internal CdpParserException(byte[] buffer, int index, string message)
            : base(message)
        {
            Buffer = buffer;
            Index = index;
        }
    }
}
