namespace libciscocdp
{
    /// <summary>
    /// A exception generated by the CDP packet parser when the input ran past the end of the buffer.
    /// </summary>
    public class CdpParserInputPastEndException : CdpParserException
    {
        /// <summary>
        /// The operation being performed when the exception occurred
        /// </summary>
        public string Operation { get; }

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="buffer">The buffer being parsed</param>
        /// <param name="index">The index within the buffer where the exception occurred</param>
        /// <param name="operation">The operation being processed when the exception occurred</param>
        /// <param name="message">The message from the parser</param>
        internal CdpParserInputPastEndException(byte[] buffer, int index, string operation, string message)
            : base(buffer, index, message)
        {
            Operation = operation;
        }
    }
}
